openapi: 3.0.3
info:
  title: Hello Counter MVP API
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
  /api/counter:
    get:
      summary: Get current counter
      responses:
        '200':
          description: Current counter value
          content:
            application/json:
              schema:
                type: object
                properties:
                  counter:
                    type: integer
                    minimum: 0
    post:
      summary: Increment counter by 1
      responses:
        '200':
          description: Updated counter value
          content:
            application/json:
              schema:
                type: object
                properties:
                  counter:
                    type: integer
                    minimum: 0
