services:
  proximeter:
    image: ghcr.io/clsferguson/proximeter:latest
    container_name: ProxiMeter
    restart: unless-stopped
    gpus: all
    ports:
      - "8000:8000"
    environment:
      - APP_PORT=${APP_PORT:-8000}
      - YOLO_MODEL=${YOLO_MODEL:-yolo11n}
      - YOLO_IMAGE_SIZE=${YOLO_IMAGE_SIZE:-320}
    volumes:
      - proximeter_config:/app/config
      - proximeter_yolo_models:/app/models
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  proximeter_config:
  proximeter_yolo_models: