openapi: 3.0.3
info:
  title: ProxiMeter Stream Management API
  description: REST API for managing RTSP streams in ProxiMeter
  version: 1.0.0
  contact:
    name: ProxiMeter Development Team

servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /streams:
    get:
      summary: List all streams
      description: Retrieve all configured streams with masked RTSP credentials
      operationId: listStreams
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StreamResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new stream
      description: Create a new RTSP stream with validation and connectivity check
      operationId: createStream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStreamRequest'
      responses:
        '201':
          description: Stream created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: Reorder streams
      description: Reorder streams by providing a new order array
      operationId: reorderStreams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReorderRequest'
      responses:
        '200':
          description: Streams reordered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /streams/{streamId}:
    patch:
      summary: Edit an existing stream
      description: Update stream name and/or RTSP URL with validation
      operationId: editStream
      parameters:
        - name: streamId
          in: path
          required: true
          schema:
            type: string
          description: Unique stream identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditStreamRequest'
      responses:
        '200':
          description: Stream updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Stream not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a stream
      description: Remove a stream and renumber remaining streams
      operationId: deleteStream
      parameters:
        - name: streamId
          in: path
          required: true
          schema:
            type: string
          description: Unique stream identifier
      responses:
        '204':
          description: Stream deleted successfully
        '404':
          description: Stream not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /streams/play/{streamId}.mjpg:
    get:
      summary: Stream MJPEG playback
      description: Get live MJPEG stream for a specific RTSP source
      operationId: playbackStream
      parameters:
        - name: streamId
          in: path
          required: true
          schema:
            type: string
          description: Unique stream identifier
      responses:
        '200':
          description: MJPEG stream
          content:
            multipart/x-mixed-replace:
              schema:
                type: string
                format: binary
        '404':
          description: Stream not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Playback error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    StreamResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique stream identifier
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Display name
        rtsp_url:
          type: string
          description: RTSP URL with credentials masked
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        order:
          type: integer
          minimum: 0
          description: Display order
        status:
          type: string
          enum: [Active, Inactive]
          description: Stream status
      required:
        - id
        - name
        - rtsp_url
        - created_at
        - order
        - status

    NewStreamRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Display name
        rtsp_url:
          type: string
          minLength: 1
          description: RTSP URL
      required:
        - name
        - rtsp_url

    EditStreamRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Display name
        rtsp_url:
          type: string
          minLength: 1
          description: RTSP URL
      minProperties: 1

    ReorderRequest:
      type: object
      properties:
        order:
          type: array
          items:
            type: string
          description: Array of stream IDs in desired order
      required:
        - order

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      required:
        - detail