name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: proximeter/hello-counter:ci

      - name: Build image locally for run
        run: |
          docker build --platform linux/amd64 -t proximeter/hello-counter:ci .

      - name: Run container
        run: |
          docker run -d --rm -p 8000:8000 --name hello-counter proximeter/hello-counter:ci
          echo "container-started" > container.txt

      - name: Wait for health
        run: |
          set -e
          for i in {1..30}; do
            code=$(curl -s -o /tmp/h.txt -w "%{http_code}" http://localhost:8000/health || true)
            body=$(cat /tmp/h.txt || true)
            if [ "$code" = "200" ] && [ "$body" = "ok" ]; then
              echo "healthy"; exit 0
            fi
            sleep 1
          done
          echo "Health check failed"; echo "Body:"; cat /tmp/h.txt || true; exit 1

      - name: Teardown
        if: always()
        run: |
          if [ -f container.txt ]; then
            docker rm -f hello-counter || true
          fi
